### ISSUE TITLE
[Bug]: There is a problem with displaying multi-database changes in dark mode

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2658]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/1ff7d8cd-a063-480e-a146-8bd63da8423d)
![image](https://github.com/oceanbase/odc/assets/143492234/a9fdd225-65b4-4b5c-9de0-2c31a8f0afd7)
![image](https://github.com/oceanbase/odc/assets/143492234/4579fec7-889b-4ec9-acd8-a63cad677e87)
![image](https://github.com/oceanbase/odc/assets/143492234/06ce8a46-54da-4620-8038-17c1e779563f)
![image](https://github.com/oceanbase/odc/assets/143492234/24e5d419-8bf4-4915-89ee-bffaaea23085)

There is a problem with displaying multi-database changes in dark mode

### What did you expect to happen?

Display normal.

### How can we reproduce it (as minimally and precisely as possible)?

Switch to dark mode and perform the multi-database change task.

**Comment by HSunboy** [comment]
Fixed In Commit [c1771da43ce0fb4f57ced3c7211e057475dd25ac](https://github.com/oceanbase/odc-client/commit/c1771da43ce0fb4f57ced3c7211e057475dd25ac)
            ------
            陈朝俊
            Thu Jun 6 16:20:14 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d74bb05d-6fa4-4f38-9cf3-6b3b0bc72564)



![Image](https://github.com/oceanbase/odc/assets/143492234/be8bfaac-0e61-493e-970f-211d476c3726)



![Image](https://github.com/oceanbase/odc/assets/143492234/6b615664-b1d7-423b-9de8-dec7c94f2767)

Still having issues

**Comment by HSunboy** [comment]
Fixed In Commit [3b7da3aa06aa98d16f789f19b626fed3f87c3b2e](https://github.com/oceanbase/odc-client/commit/3b7da3aa06aa98d16f789f19b626fed3f87c3b2e)
            ------
            xiaokang
            Fri Jun 7 10:56:24 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/f421dca9-0f3c-49b0-aaa0-65d727f88346)



![Image](https://github.com/user-attachments/assets/1df72406-ca66-4091-a5cd-765449b48325)

The problem still exists

**Comment by HSunboy** [comment]
Fixed In Commit [0b81dd6e73f475787e2b33460e21435f91fd740e](https://github.com/oceanbase/odc-client/commit/0b81dd6e73f475787e2b33460e21435f91fd740e)
            ------
            xiaokang
            Fri Jul 26 14:10:45 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/f8910344-792e-43b3-a44a-b4258f29db98)



![Image](https://github.com/user-attachments/assets/513b3157-1d3b-4389-bcd3-246ae9ac546d)

pass
