### ISSUE TITLE
[Bug]: Right click on the database to expand without permission request

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3165]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/221d11e2-8b03-4337-85d2-4cdc313fbdfe)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/aadfb45f-7033-40ba-8e1f-702c43b0ffeb)

### How can we reproduce it (as minimally and precisely as possible)?

Right click to expand the database

**Comment by HSunboy** [comment]
Fixed In Commit [a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471](https://github.com/oceanbase/odc-client/commit/a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471)
            ------
            畅晚
            Wed Sep 4 09:54:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/e6e172dc-9f4f-40ca-88af-4358bb79aeb6)



![Image](https://github.com/user-attachments/assets/cd0083d0-9ea0-468a-a2d7-7b5279cf0e53)

The problem still exists

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c4139f7b-6500-4372-a6f5-13218b8e4a17)

pass

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/4ebdf96d-1424-4685-9cc5-952fdf01b3bf)

pass
